# name: CI - Heroku

# on:
#   workflow_run:
#     workflows:
#       - "CI - Build"
#     branches:
#       - main
#     types: 
#       - completed

# env:
#   APP_NAME: lifeweb-docker
#   HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

# jobs:
#   push_web:
#     name: "CI - Heroku: Push (web)"
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
#       - 
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GHCR_PAT }}
#       - 
#         run: heroku container:login
#       -
#         run: docker pull ghcr.io/lifeweb360/lifeweb:main
#       -
#         run: docker tag ghcr.io/lifeweb360/lifeweb:main $(echo registry.heroku.com/$APP_NAME/web)
#       -
#         run: docker push $(echo registry.heroku.com/$APP_NAME/web)

#   push_worker:
#     name: "CI - Heroku: Push (worker)"
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Checkout
#         uses: actions/checkout@v2
#       # - 
#       #   name: Replace Dockerfile
#       #   run: rm Dockerfile && mv platform/docker/Docker.worker Dockerfile
#       -
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GHCR_PAT }}
#       - 
#         run: heroku container:login
#       -
#         run: docker pull ghcr.io/lifeweb360/lifeweb:main
#       -
#         run: docker tag ghcr.io/lifeweb360/lifeweb:main $(echo registry.heroku.com/$APP_NAME/worker)
#       -
#         run: docker push $(echo registry.heroku.com/$APP_NAME/worker)