name: CI - Rebuild

on:
  push:
    branches:
      - main
    paths:
      - Gemfile.lock
      - yarn.lock
      - platform/docker/Docker.builder
      - platform/docker/Docker.final
env:
  RUBY_VERSION: '3.0.1'
  NODE_VERSION: '16.x'
  BUILD_MODE: true
  DOCKER_REPO: ghcr.io/mileszim/rails-base-builder

jobs:
  rebuild:
    name: CI - Rebuild
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      -
        name: Build and push base-builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          file: platform/docker/Docker.builder
          tags: ${{ env.DOCKER_REPO }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        name: Build and push rails-base-final
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: platform/docker/Docker.final
          tags: ${{ env.DOCKER_REPO }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache